
version: "3"

services:

  splunk:
    image: dmuth1/splunk-lab
    restart: "unless-stopped"
    privileged: true
    volumes:
      #- /var/log:/logs/
      - ./logs:/logs/
      - ./data:/data
      - .:/mnt
      - ./app:/app
    environment:
      - TZ=EST5EDT
    ports:
      - 8000:8000
    environment:
      - TZ=EST5EDT


